
# Deck the Halls
```
Deck the halls with boughs of holly
Fa-la-la-la-la, la-la-la-la
'Tis the season to be jolly
Fa-la-la-la-la, la-la-la-la

  Don we now our gay apparel
  Fa-la-la, la-la-la, la-la-la.
  Troll the ancient Yule-tide carol
  Fa-la-la-la-la, la-la-la-la.
```

## Falalalala
```
Dans les villes et les villages 
Fa-la-la-la-la, la-la-la-la
Répandons notre message 
Fa-la-la-la-la, la-la-la-la

  Proclamons la joie profonde 
  Fa-la-la, la-la-la, la-la-la
  Que Dieu a donné au monde 
  Fa-la-la-la-la, la-la-la-la

Que l'on chante qu'on s'apprête
Fa la la la la la la la la
Sonnez pipeaux et trompettes
Fa la la la la la la la la

  Car c'est la joie qu'on apporte
  Fa la la la la la la la la
  Ouvrez donc grandes vos portes
  Fa la la la la la la la la
```

## Chords
```
C  G  C 
C  G  C

  G C F C
  C  G  C
```

# Jingle Bells  
```
Dashing through the snow
In a one horse open sleigh
Over fields we go
Laughing all the way
Bells on bob tails ring
Making spirits bright
What fun it is to laugh and sing
A sleighing song tonight

  Oh, jingle bells, jingle bells
  Jingle all the way
  Oh, what fun it is to ride
  In a one horse open sleigh 
  (x2)
```

## Vive le vent
```
Sur le long chemin 
Tout blanc de neige blanche 
Un vieux monsieur s'avance 
Avec sa canne dans la main 
Et tout là-haut le vent 
Qui siffle dans les branches 
Lui souffle la romance 
Qu'il chantait petit enfant:

  Vive le vent, vive le vent 
  Vive le vent d'hiver 
  Qui s'en va sifflant, soufflant 
  Dans les grands sapins verts 
  OH! Vive le temps, vive le temps 
  Vive le temps d'hiver 
  Boule de neige et jour de l'an 
  Et bonne année grand-mère ... 

    Joyeux joyeux Noël 
    aux mille bougies 
    qu'enchantent vers le ciel   
    les cloches de la nuit.
    
  Vive le vent, vive le vent,
  Vive le vent d'hiver 
  qui rapporte aux vieux enfants
  un souvenir d'hier.
```

## Chords
```
C
Dm
G
C

C C
C C
F C
D G
```

# Mon beau sapin
```
Mon beau sapin, roi des forêts 
Que j'aime ta verdure! (x2)

  Quand, par l'hiver, bois et guérets 
  Sont dépouillés de leurs attraits 
  Mon beau sapin, roi des forêts 
  Tu gardes ta parure.
```

##  Christmas Tree 
```
O Christmas tree, O Christmas tree
Your leaves are so unchanging (x2)

  Not only green when Summer’s here
  But also when it’s cold and drear
  O Christmas tree, O Christmas tree
  Your leaves are so unchanging
```

## O Tannenbaum 
```
 O Tannenbaum, o Tannenbaum,
 Dein Kleid will mich was lehren: (x2)
 
   Die Hoffnung und Beständigkeit
   Gibt Mut und Kraft zu jeder Zeit!
   O Tannenbaum, o Tannenbaum,
   Dein Kleid will mich was lehren!
```

### Chords
```
```


# We wish you a Merry Christmas 
```
We wish you a Merry Christmas (x3)
And a Happy New Year

  Good tidings we bring
  To you and your kin
  We wish you a Merry Christmas
  And a Happy New Year

Now bring us some figgy pudding (x3)
And a cup of good cheer
```

## On se dit Joyeux Noël
```
Je te dis joyeux Noël 
Tu me dis joyeux Noël 
On se dit joyeux Noël 
Et aussi bonne année

  A tout' la famille
  On dit joyeux Noël
  Et nos voeux pour que brille
  La nouvelle année

J'apporte un petit gâteau 
Tu apportes un petit gâteau 
On apporte un petit gâteau 
Petits gâteaux sucrés

Je donne un petit baisé
Tu donnes un petit baisé
On donne un petit baisé
Petits baisers mouillés

Et je ne partirai pas 
Et tu ne partiras pas 
Et on ne partira pas 
Avant davoir chanté
```

### Chords
```
```



# Santa Claus is Coming to Town
```
You better watch out, you better not cry
Better not pout, I'm telling you why
Santa Claus is comin' to town

He's making a list and checking it twice
Gonna find out who's naughty and nice
Santa Claus is comin' to town

  He sees you when you're sleepin'
  He knows when you're a wake
  He knows if you've been bad or good
  So be good for goodness sake
```

## Père Noël Arrive ce Soir
```
J’ai vu dans la nuit passer un traîneau, 
et j’ai vu aussi ton grand ami
Père Noël arrive ce soir

II allait vers toi dans la cheminée, 
il allait vers toi pour y déposer
Des jouets dans ton bas ce soir. 

  Et bien tu devras dormir 
  sans te faire aucun souci
  Même si tu n’en as pas envie,
  tu devras rester au lit.
```

### Chords
```
C F
C F
C G C

  F 
  Am 
  D7 
  G
```


# Le p’tit renne au nez rouge 
```
(Quand la neige recouvre la verte Finlande 
Et que les rennes traversent la lande 
Le vent dans la nuit 
Au troupeau parle encore de lui) 

 On l'appelait Nez rouge
 Ah comme il était mignon !
 Le p'tit renne au nez rouge
 Rouge comme un lumignon

 Son p'tit nez faisait rire
 Chacun s'en moquait beaucoup
 On allait jusqu'à dire
 Qu'il aimait prendre un p'tit coup.
 
   Une fée qui l'entendit 
   Pleurer dans le noir
   Pour le consoler lui dit:
   Viens au paradis ce soir

 Comme un ange, Nez rouge
 Tu conduiras dans le ciel
 Avec ton p'tit nez rouge
 Le chariot du Père Noël !  
 
(Quand ses frères le virent D'allure si leste
Suivre, très digne les routes célestes
Devant ses ébats
Plus d'un renne resta baba. )
 
 Couplet 1,
 Maintenant qu'il entraîne
 Son char à travers les cieux
 C'est lui le roi des rennes
 Et son nez fait des envieux. 

   Vous, fillettes et garçons
   Pour la grande nuit
   Si vous savez vos leçons
   Dès que sonnera minuit
 
 Ce petit point qui bouge
 Ainsi qu'une étoile au ciel
 C'est le nez de Nez rouge
 Annonçant le Père Noël ! 
```

## Rudolph the red-nosed reindeer
```
Rudolph the Red Nosed Reindeer 
Had a very shiny nose, 
And if you ever saw it, 
You would even say it glows. 

All of the other reindeer 
Used to laugh and call him names; 
They never let poor Rudolph 
Join in any reindeer games.

  Then one foggy Christmas Eve, 
  Santa came to say, 
  Rudolph with your nose so bright, 
  Won't you guide my sleigh tonight?
  
All of the reindeer loved him,
And they shouted out with glee
Rudolph the Red Nosed Reindeer
You’ll go down in History! X2
```


### Chords
```
```



# C’est l’hiver
```
Nous filons sur la neige blanche
En ce beau jour de dimanche
À travers les sapins verts
C'est l'hiver, c'est l'hiver, c'est l'hiver

Les enfants de notre village
Chantent la joie de leur âge
Et les grands murmures de se taire
C'est l'hiver, c'est l'hiver, c'est l'hiver

  Le bon Dieu dans son paradis
  Doit aussi chanter avec nous
  Car la nature est si jolie
  Le bleu de son ciel est si doux
```

## Let it snow
```
Oh, the weather outside is frightful
But the fire is so delightful
And since we've no place to go
Let it snow, let it snow, let it snow

Man it doesn't show signs of stoppin'
And I brought some corn for poppin'
The lights are turned way down low
Let it snow, let it snow, let it snow

  When we finally kiss goodnight
  How I’ll hate going out in the storm
  And if you only hold me tight,
  All the way home I’ll be warm

The fire is slowly dying
And my dear we're still goodbye-ing
As long as you love me so
Let it snow, let it snow, let it snow
```



# Petit Papa Noël
```
(C'est la belle nuit de Noël
La neige étend son manteau blanc
Et les yeux levés vers le ciel
À genoux, petits enfants
Avant de fermer les paupières
Font une dernière prière)

Petit papa Noël
Quand tu descendras du ciel
Avec des jouets par milliers
N'oublie pas mon petit soulier.

Mais avant de partir
Il faudra bien te couvrir
Dehors tu vas avoir si froid
C'est un peu à cause de moi.

  Il me tarde tant que le jour se lève
  Pour voir si tu m'as apporté
  Tous les beaux joujoux que je vois en rêve
  Et que je t'ai commandés.

Petit papa Noël
Quand tu descendras du ciel
Avec des jouets par milliers
N'oublie pas… 

Petit papa Noël
Quand tu descendras du ciel
Avec des jouets par milliers
N'oublie pas mon petit soulier.

  Et quand tu seras sur ton beau nuage
  Viens d'abord sur notre maison
  Je n'ai pas été tous les jours très sage
  Mais j'en demande pardon.

Petit papa Noël
Quand tu descendras du ciel
Avec des jouets par milliers
N'oublie pas mon petit soulier.
Petit papa Noël
```

## Chords
```
C
Am
G F
C
F C
G G7 C


C
C (Fm) C
F C
D G


Am F
Am G
G# A#
D# F G

```


# Feliz Navidad 
```
feliz navidad (x3)
prospero año y felicidad 

  I wanna wish you a merry Christmas (x3)
  From the bottom of my heart
```


## Chords
```
```

# Jingle Bell Rock

```
Jingle bell, jingle bell, jingle bell rock
Jingle bells swing and jingle bells ring
Snowing and blowing up bushels of fun
Now the jingle hop has begun

Jingle bell, jingle bell, jingle bell rock
Jingle bells chime in jingle bell time
Dancing and prancing in Jingle Bell Square
In the frosty air

  What a bright time, it's the right time
  To rock the night away
  Jingle bell time is a swell time
  To go gliding in a one-horse sleigh
  
Giddy-up jingle horse, pick up your feet
Jingle around the clock
Mix and a-mingle in the jingling feet
That's the jingle bell rock

Jingle bell, jingle bell, jingle bell rock
Jingle bells chime in jingle bell time
Dancing and prancing in Jingle Bell Square
In the frosty air

Jingle bell, jingle bell, jingle bell rock
Jingle bells chime in jingle bell time
Snowing and blowing up bushels of fun
Now the jingle hop has begun

Jingle bell, jingle bell, jingle bell rock
Jingle bells chime in jingle bell time
Dancing and prancing in Jingle Bell Square
In the frosty air

  What a bright time, it's the right time
  To rock the night away (rock the night away)
  Jingle bell time is a swell time
  To go gliding in a one-horse sleigh
  
Giddy-up jingle horse, pick up your feet
Jingle around the clock
Mix and a-mingle in the jingling feet
That's the jingle bell
That's the jingle bell
That's the jingle bell (rock)
```

### Chords
```
```


# Douce Nuit Sainte Nuit 

```
Be-elle nuit, sain-ainte nuit !
Tout s'endort, plus de bruit.
 Veille seu-eul, le   couple sacré
 Doux enfan-ant aux   fin-ins cheveux
  Clos tes   yeux et re  po--s   e.
  Sou-ous ces yeux vigilants.
 
Be-elle nuit, sain-ainte nuit ! 
Dans les champs, les bergers, 
Par les an-anges a-avertis, 
Font partou-out retentir leur voix : 
Le sauveur vient de naî-aî-tre 
Le-e sauveu-eur est là ! 
 
3. Be-elle nuit, sain-ainte nuit ! 
Mon Jésus bien aimé, 
Quel souri-ire dan-ans tes yeux, 
Tan-andis que pour l'ho-o-om-me 
So-onne l'heure sainte, 
L'heu-eure du-u salut ! 
```

## Silent night 
```
Silent night, holy night! 
All is calm, all is bright. 
Round yon Virgin, Mother and Child. 
Holy infant so tender and mild, 
Sleep in heavenly peace, 
Sleep in heavenly peace. 

Silent night, holy night! 
Shepherds quake at the sight. 
Glories stream from heaven afar 
Heavenly hosts sing Alleluia, 
Christ the Savior is born! 
Christ the Savior is born. 

Silent night, holy night! 
Son of God love's pure light. 
Radiant beams from Thy holy face 
With dawn of redeeming grace, 
Jesus Lord, at Thy birth. 
Jesus Lord, at Thy birth.
```

## Chords
```
```

# Walking in a winter wonderland 
```
Sleigh bells ring
Are you listening
In the lane
Snow is glistening
A beautiful sight,
We're happy tonight
Walking in a winter wonderland

  In the meadow we can build a snowman
  nd pretend that he is Parson Brown
  He'll say are you married, We'll say no man
  But you can do the job When you're in town
  
Later on
We'll conspire
As we dream by the fire
To face unafraid
The plans that we've made
Walking in a winter wonderland
```

## Chords
```
C
C
G
G
G7
G G7 C

E H E
E H E
G D G
G D G
```


## Bonhomme hiver
```
Écoutez les clochettes
Du joyeux temps des fêtes
Annonçant la joie
Dans chaque cœur qui bat
Au royaume du bonhomme hiver

  Le voilà qui sourit sur la place
  Son chapeau, sa canne et son foulard
  Il semble nous dire d'un ton bonasse:
  "Ne voyez-vous donc pas qu'il est tard?"

Il dit vrai tout de même
Près du feu, je t'emmène
Allons nous chauffer dans l'intimité
Au royaume du bonhomme hiver
```		




# Frosty the Snowman 
```
Frosty the Snowman, Was a jolly happy soul
With a corncob pipe and a button nose
And his eyes made out of coal

Frosty the Snowman, Made the children laugh and play
And were they surprised when
Before their eyes
He came to life that day

  There must have been some magic
  In that old silk hat they found
  For when they placed it on his head
  He began to dance around

Frosty the Snowman, Was alive as he could be
And the children say
He could laugh and play
Just the same as you and me

Frosty the Snowman, Knew the sun was hot that day
So he said let's run
And we'll have fun
Now before I melt away

So down to the village
With a broomstick in his hand
Running here and there all around the square
Saying catch me if you can
He led… 
He led them down the streets of town
Right to the traffic cop
And he only paused a moment when
He heard him holler stop

Frosty the Snowman, Had to hurry on his way
But he waved goodbye
Saying don't you cry
I'll be back again some day
Thumpety thump thump
Thumpety thump thump
Look at Frosty go
Thumpety thump thump
Thumpety thump thump
Over the hills of snow
```

## Chords
```
```


## Frosty le bonhomme
```
Frosty le bonhomme, le gentil bonhomme d’hiver
Avec son nez de carotte et ses yeux de boutons
C’est l’ami des p’tits enfants

Frosty le bonhomme, le gentil bonhomme de neige
Avec son nez de carotte et ses yeux de boutons
C’est l’ami du Père Noël

Son chapeau et son foulard
Il marche dans la rue
Et quand il voit les p’tits enfants
Il leur fait des grands saluts

Frosty le bonhomme, le gentil bonhomme d’hiver
Avec son nez de carotte et ses yeux de boutons
C’est l’ami des p’tits enfants

Frosty le bonhomme, le gentil bonhomme de neige
Avec son nez de carotte et ses yeux de boutons
C’est l’ami du Père Noël

Son chapeau et son foulard
Il marche dans la rue
Et quand il voit les p’tits enfants
Il leur fait des grands saluts

Frosty le bonhomme, le gentil bonhomme d’hiver
Avec son nez de carotte et ses yeux de boutons
C’est l’ami du Père Noël
Frosty,frosty
Frosty le bonhomme, le gentil bonhomme d’hiver
```


# All I want for Christmas is you 

```
I don't want a lot for Christmas
There's just one thing I need
I don't care about the presents
Underneath the Christmas tree
I just want you for my own
More than you could ever know
Make my wish come true
All I want for Christmas is...
You

I don't want a lot for Christmas
There's just one thing I need
I don't care about the presents
Underneath the Christmas tree
I don't need to hang my stocking
There upon the fireplace

Santa Claus won't make me happy
With a toy on Christmas day
I just want you for my own
More than you could ever know
Make my wish come true
All I want for Christmas is you
You       baby

I won't ask for much this Christmas
I don't even wish for snow
I'm just gonna keep on waiting
Underneath the mistletoe
I won't make a list and send it
To the North Pole for Saint Nick
I won't even stay awake to
Hear those magic reindeers click

'Cause I just want you here tonight
Holding on to me so tight
What more can I do
Baby all I want for Christmas is 
you     Ooh baby

[Bridge]
B7
All the lights are shining
   Em
So brightly everywhere
B7
And the sound of children's
Em
Laughter fills the air
Cm
And everyone is singing
G            E7
I hear those sleigh bells ringing
Am7
Santa won't you bring me the one I really need
          C
Won't you please bring my baby to me...
   G
Oh I don't want a lot for Christmas
This is all I'm asking for
C
I just want to see my baby
Cm
Standing right outside my door

Oh I just want you for my own
More than you could ever know
Make my wish come true
     Baby all I want for Christmas is...
You
```


## Chords
```
```


# Promenade en traîneau
```
Au petit trot s'en va le cheval avec ses grelots 
et le traîneau joyeusement dévale à travers les coteaux. 
Dans le vallon s'accroche l'hiver mais le ciel est bleu. 
Ah! Qu'il fait bon faire un tour au grand air comme des amoureux. 

  Ho di up ho di up ohé, ohé du traîneau 
  Emmitouflez-vous bien dans vos manteaux 
  Ho di up ho di up ohé pour se tenir chaud 
  L'un contre l'autre on se blottit comme deux moineaux dans un nid. 

C'est merveilleux de voir défilant comme un décor peint, 
Devant nos yeux les villages tout blancs et les petits sapins. 
Parfois tu cries car ça penche un peu, c'est l'instant d'effroi, 
moi je souris, j'ai le cœur amoureux et le bout du nez froid. 

    L'attelage a déjà  pris le chemin du retour. 
    Nous allons être surpris par la tombée du jour, 
    car c'est l'heure où la nuit sans bruit s'épanouit comme une fleur 
    et s'allume le ciel qui change de couleurs. 

    Mais voici notre maison qui nous fait signe au loin, 
    sa lumière à  l'horizon scintille comme un point. 
    Je me vois déjà  près de toi le rire aux yeux, le cœur content, 
    près du grand feu de bois qui flambe et nous attend. 

Au petit trot s'en va le cheval avec ses grelots 
et le traîneau joyeusement dévale à  travers les coteaux...
```

## Sleigh Ride
```
Just hear those sleigh bells jingling, ring ting tingling too
Come on, it's lovely weather for a sleigh ride together with you,
Outside the snow is falling and friends are calling "Yoo hoo,"
Come on, it's lovely weather for a sleigh ride together with you.

  Giddy up, giddy up, giddy up, let's go, Let's look at the show,
  We're riding in a wonderland of snow.
  Giddy up, giddy up, giddy up,it's grand, Just holding your hand,
  We're gliding along with a song of a wintry fairy land.

Our cheeks are nice and rosy
and comfy cozy are we
We're snuggled up together
like two birds of a feather would be
Let's take that road before us
and sing a chorus or two
Come on, it's lovely weather
for a sleigh ride together with you.

    There's a birthday party at the home of Farmer Gray
    It'll be the perfect ending a perfect day
    We'll be singing the songs we love to sing without a single stop,
    At the fireplace while we watch the chestnuts pop. Pop! pop! pop!
    
    There's a happy feeling nothing in the world can buy,
    When they pass around the chocolate and the pumpkin pie
    It'll nearly be like a picture print by Currier and Ives
    These wonderful things are the things we remember all through our lives!
```

## Chords

```
Intro:  | Cm7  Am | F  G7  |  
  
     G7           Cm7         Am        F        
Just hear those sleigh bells jingling,
G7      Cm7  Am  F
ring-ting-tingling too.
  
     G7       Cm7    Am             F             G7 
Come on, it's lovely weather for a sleigh
       Cm7  Am  F
ride together with you.
  
   G7       Cm7     Am           F            G7        
Outside the snow is falling and friends are
Cm7  Am  F
calling 'You Hoo!'
  
     G7        Cm7    Am           F             G7  
Come on, it's lovely weather for a sleigh
       C  F  C
ride together with you.
  
  
      F#m7                           B7  E        
Giddy-yap giddy-yap, giddy-yap, let's go,    
  
      Cdim         E6  
Let's look at the snow.   
  
A      F#m        A      B7      E     E6   E   E6  
We're riding in a wonderland of snow.   
  
      Em        B+         Em7       A7   Dm7   
Giddy-yap giddy-yap, giddy-yap, it's grand      
  
     F#m7         D6  
Just holding your hand.   
  
Dm7            G7                      Cdim  
We're gliding along with the song
Fdim   G7
of a wintry fairy land.
  
  
     Fdim      Cm7      Am       F 
Our cheeks are nice and rosy
    G7      Cm7  Am  F
and comfy cozy are we.
  
       G7      Cm7  Am              F           G7      
We're snuggled up together like two birds
   Cm7  Am  F
of a feather would be.
  
       G7      Cm7     Am          F     G7        
Let's take the road before us and sing a
Cm7  Am  F
chorus or two.
  
     G7       Cm7    Am             F            G7  
Come on, it's lovely weather for a sleigh
       C   F  C
ride together with you.
  
  
          G        Am7  G/B      C      G  D9 
There's a birthday party at the home
 G
of farmer Gray.
  
     G        Am7    G/B    C     G  D9   G6  
It'll be the perfect ending of a perfect day.   
  
 Am7      Em                   Am     Cdim    B7    
We'll be singing the songs we love to sing
B7/F#   Em
without a single stop
  
        A                  E7                 A  
At the fireplace while we watch
    D7
the chestnuts pop -- Pop! Pop! Pop!
  
  
          G      Am7    G/B     C      G     D9  
There's a happy feeling nothing in the
G
world can buy
  
           G     Am7      G/B    C        G  D9  
When they pass around the coffee and
G6
the pumpkin pie.
  
Am7   G                 Am     D7      Cdim     B7 
It'll nearly be like a picture print by Currier
    Em
and Ives.
  
G     Am7        G             Am7       
These wonderful things are the
 G
things we remember
  
      Am7        G  
All through our lives.  
  
A     Em7        A              Em7      
These wonderful things are the
 A
things we remember
  
     Em7         A  
All through our lives.  
  
  
     A7           Dm7         D6       G/B      
Just hear those sleigh bells jingling,
 A7      Dm7  D6 G/B
ring-ting-tingling too,
  
     A7        Dm7    D6           G/B           A7 
Come on, it's lovely weather for a sleigh
        D  Bm  G6
ride together with you,
  
    A7       Dm7     D6         G/B         A7          
Outside the snow is falling and friends are
Dm7  D6 G/B
calling 'You Hoo!'
  
 A7           Dm7     D6           G/B            A7
Come on, it's lovely weather for a sleigh
         Dm7 G/B  D6
ride together with you.

```

# Il est né le divin enfant 

```
Il est né le divin enfant, 
Jouez hautbois, résonnez musettes ! 
Il est né le divin enfant, 
Chantons tous son avènement ! 

Depuis plus de quatre mille ans, 
Nous le promettaient les prophètes 
Depuis plus de quatre mille ans, 
Nous attendions cet heureux temps. 

Il est né le divin enfant, 
Jouez hautbois, résonnez musettes ! 
Il est né le divin enfant, 
Chantons tous son avènement ! 

Ah ! Qu'il est beau, qu'il est charmant ! 

Ah ! que ses grâces sont parfaites ! 
Ah ! Qu'il est beau, qu'il est charmant ! 
Qu'il est doux ce divin enfant ! 

Il est né le divin enfant, 
Jouez hautbois, résonnez musettes ! 
Il est né le divin enfant, 
Chantons tous son avènement ! 

Une étable est son logement 
Un peu de paille est sa couchette, 
Une étable est son logement 
Pour un dieu quel abaissement ! 

Il est né le divin enfant, 
Jouez hautbois, résonnez musettes ! 
Il est né le divin enfant, 
Chantons tous son avènement ! 

Partez, grands rois de l'Orient ! 
Venez vous unir à  nos fêtes 
Partez, grands rois de l'Orient ! 
Venez adorer cet enfant ! 
```


## Chords
```
```


# L'enfant au tambour

```
Sur la route, 
 Pa-ram-pam-pam-pam 
 Petit tambour s'en va. 
 Pa-ram-pam-pam-pam 
 Il sent son coeur qui bat 
 Pa-ram-pam-pam-pam 
 Au rythme de ses pas 
 Pa-ram-pam-pam-pam-ram-pam-pam-pam ram-pam-pam-pam 
 Ô petit enfant, 
 Pa-ram-pam-pam-pam 
 Où vas-tu ? 

 Hier mon père 
 Pa-ram-pam-pam-pam 
 A suivi le tambour 
   Pa-ram-pam-pam-pam 
 Le tambour des soldats 
 Pa-ram-pam-pam-pam 
 Alors je vais au ciel 
 Pa-ram-pam-pam-pam-ram-pam-pam-pam ram-pam-pam-pam 

Là je veux donner pour son retour 
 Mon tambour 
 Tous les anges 
 Pa-ram-pam-pam-pam 
 Ont pris leurs beaux tambours 
 Pa-ram-pam-pam-pam 
 Et on dit à l'enfant 
 Pa-ram-pam-pam-pam 
 Ton père est de retour 
 Pa-ram-pam-pam-pam-ram-pam-pam-pam ram-pam-pam-pam 
  
 Et l'enfant s'éveille 
 Pa-ram-pam-pam-pam 
 Sur son tambour 
 Sur son tambour 
 Sur son tambour 
 Sur son tambour
``` 

## Drummer Boy
```
Come, they told me
Pa rum pum pum pum
Our newborn King to see
Pa rum pum pum pum
Our finest gifts we bring
Pa rum pum pum pum
To lay before the King
Pa rum pum pum pum
Ra pum pum pum
Ra pum pum pum
Ra pum pum pum
Ra pum pum pum pum pum
Yeah, I'm on the drum
Yeah, I'm on the stand drum
Yeah, I'm on the beat 'cause the beat goes dumb
And they only spare heat 'cause I'm playing for the sun
Playing for the King, playing for the title
I'm surprised you didn't hear this in the Bible
I'm so tight I might go psycho
Christmas time so here's a recital
I'm so bad like Michael I know
I'm still young but I go I go
Stupid, stupid, love like cupid
I'ma drummer boy so do, do
Little baby
Pa rum pum pum pum
I am a poor boy too
Pa rum pum pum pum (gather round the mistletoe real quick)… 
```

## Chords
```
```


# I Saw Mommy Kissing Santa Claus" 

```
Wow, mommy's kissing Santa Claus
I saw Mommy kissing Santa Claus
Underneath the mistletoe last night
She didn't see me creep
Down the stairs to have a peep
She thought that I was tucked up
In my bedroom, fast asleep

Then I saw mommy tickle Santa Claus
Underneath his beard so snowy white
Oh, what a laugh it would have been
If Daddy had only seen
Mommy kissing Santa Claus last night

He saw mommy kissing, kissin', kissin' Santa Claus
I did, I really did see mommy kissing Santa Claus
And I'm gonna tell my dad



Then I saw mommy tickle Santa Claus
Underneath his beard so snowy white
Oh, what a laugh it would have been
If daddy had only seen
Mommy kissing Santa Claus last night

Oh, what a laugh it would have been
If Daddy had only seen
Mommy kissing Santa Claus last night

I did, I did, I really did see mommy kissing Santa Claus
You gotta believe me, you just gotta believe me
Come on, fellas, believe me, you just gotta believe me
```



## Chords
```
```

## J'ai vu maman embrasser le Père Noël


```
C'est Noël, et comme chaque année
Le petit Jojo a des joujoux plein sa ch'minée
Mais depuis la nuit même il a aussi un secret
À son nounours qu'il aime, il murmure: 
Si tu savais...
- 1 -
Moi j'ai vu petite maman hier soir
En train d'embrasser le Père Noël
Ils étaient sous le gui
Et me croyaient endormi
Mais sans en avoir l'air
J'avais mes deux yeux entr'ouverts
Ah! si papa était v'nu à passer
Je m' demande ce qu'il aurait pensé
Aurait-il trouvé naturel
Parce qu'il descend du ciel
Que maman embrasse le Père Noël ?
- 2 -
Quand j'ai vu petite maman hier soir
En train d'embrasser le Père Noël
J'ai bien cherché pourquoi
Et j'ai deviné je crois
C'est parce qu'il m'avait
Apporté de si beaux jouets
Aussi pour l'an prochain j'ai bon espoir
Qu'il viendra encore à mon appel
Et de nouveau je f'rai semblant
De dormir profondément
Si maman embrasse le Père Noël.

Et de nouveau je f'rai semblant
De dormir profondément
Si maman embrasse le Père Noël.
```


# "Wonderful Christmas time" (MacCarthney)

```
The moon is right
The spirit’s up
We’re here tonight
And that’s enough

Simply having a wonderful Christmas time
Simply having a wonderful Christmas time

The party’s on
The feelin’s here
That only comes
This time of year

Simply having a wonderful Christmas time
Simply having a wonderful Christmas time

The choir of children sing their song
Ding dong, ding dong
Ding dong, ding, oh, oh

Simply having a wonderful Christmas time
Simply having a wonderful Christmas time

The word is out
About the town
To lift a glass
Ah, don’t look down

Simply having a wonderful Christmas time
Simply having a wonderful Christmas time

The choir of children sing their song
They practiced all year long

Ding dong, ding dong
Ding dong, ding dong
Ding dong, ding dong


The party’s on
The spirit’s up
We’re here tonight
And that’s enough

Simply having a wonderful Christmas time
Simply having a wonderful Christmas time

The moon is right
The spirit’s up
We’re here tonight
And that’s enough

Simply having a wonderful Christmas time
Simply having a wonderful Christmas time
Simply having a wonderful Christmas time
Simply having a wonderful Christmas time

Oh, Christmas time
```

# Run Rudolph Run 


```
Out of all the reindeers you know you're the mastermind
Run, run Rudolph, Randalph ain't too far behind
Run, run Rudolph, Santa's got to make it to town
Santa make him hurry, tell him he can take the freeway down
Run, run Rudolph 'cause I'm reelin' like a merry-go-round

Said Santa to a boy child what have you been longing for?
All I want for Christmas is a rock and roll electric guitar
And then away went Rudolph a whizzing like a shooting star
Run, run Rudolph, Santa's got to make it to town
Santa make him hurry, tell him he can take the freeway down
Run, run Rudolph, reeling like a merry-go-round


Run, run Rudolph, Santa's got to make it to town
Santa make him hurry, tell him he can take the freeway down
Run, run Rudolph, reeling like a merry-go-round

Said Santa to a girl child what would please you most to get?
A little baby doll that can cry, sleep, drink and wet
And then away went Rudolph a whizzing like a Saber jet
Run, run Rudolph, Santa's got to make it to town
Santa make him hurry, tell him he can take the freeway down
Run, run Rudolph 'cause I'm reelin' like a merry-go-round
```





# Les anges dans nos campagnes 

```
Les anges dans nos campagnes 
Ont entonné l'hymne des cieux, 
Et l'écho de nos montagnes 
Redit ce chant mélodieux 

Gloria in excelsis Deo 
Gloria in excelsis Deo 

Bergers, pour qui cette fête ? 
Quel est l'objet de tous ces chants ? 
Quel vainqueur, quelle conquête 
Mérite ces cris triomphants : 

Gloria in excelsis Deo 
Gloria in excelsis Deo 

Ils annoncent la naissance 
Du libérateur d'Israël 
Et pleins de reconnaissance 
Chantent en ce jour solennel : 

Gloria in excelsis Deo 
Gloria in excelsis Deo 



Cherchons tous l'heureux village 
Qui l'a vu naître sous ses toits 
Offrons-lui le tendre hommage 
Et de nos cœurs et de nos voix : 

Gloria in excelsis Deo 
Gloria in excelsis Deo 

Bergers, quittez vos retraites, 
Unissez-vous à  leurs concerts, 
Et que vos tendres musettes 
Fassent retentir dans les airs 

Gloria in excelsis Deo 
Gloria in excelsis Deo
```

## Angels We've Heard On (In Excelsis Deo)
```
ENGLISH: 
Angels we have heard on high,
Singing sweetly through the night,
And the mountains in reply
Echoing their brave delight.
Gloria in excelsis Deo.
Gloria in excelsis Deo.

Shepherds, why this jubilee?
Why these songs of happy cheer?
What great brightness did you see?
What glad tiding did you hear?
Gloria in excelsis Deo.
Gloria in excelsis Deo.

Come to Bethlehem and see
Him whose birth the angels sing;
Come, adore on bended knee
Christ, the Lord, the new-born King.
Gloria in excelsis Deo.
Gloria in excelsis Deo.

See him in a manger laid
Whom the angels praise above;
Mary, Joseph, lend your aid,
While we raise our hearts in love.
Gloria in excelsis Deo.
Gloria in excelsis Deo.
```




# Voici le Père Noël 

```
- 1 -
 Voici le Père Noël (bis)
 Qui revient parmi nous. 
 Qui m'apporte mille sortes
 De présents, de joujoux
 C'est ce soir que les petits
 Et même les grands
 Verront leurs désirs se changer
 En plaisirs attrayants. 

- 2 -
 Voici le Père Noël (bis)
 Qui revient parmi nous. 
 Les cloches sonnent, carillonnent
 Partout alentour
 On entend des chants joyeux
 Des voix douces d'enfants
 Qui chantent, l'air radieux 
 Et le coeur content. 

- 3 -
 Voici le Père Noël (bis)
 Qui revient parmi nous. 
 Les plus riches, il s'en fiche
 Il nous aime tous
 Ce qui compte à ses yeux
 C'est de faire des heureux
 Il aime surtout les enfants
 Qui sont obéissants. 

 Voici le Père Noël (bis)
 Qui revient parmi nous.
```


## Chords
```
```


## Here Comes Santa Claus 
```
Here Comes Santa Claus (Right Down Santa Claus Lane)
Here comes Santa Claus, here comes Santa Claus right down Santa Claus Lane
Vixen and Blitzen and all his reindeer pullin' on the reins
Bells are ringin', children singin', all is merry and bright
So hang your stockings and say your prayers 'cause Santa Claus comes tonight

Here comes Santa Claus, here comes Santa Claus right down Santa Claus Lane
He's got a bag that's filled with toys for boys and girls again
Hear those sleigh bells jingle jangle, oh what a beautiful sight
So jump in bed, and cover your head, 'cause Santa Claus comes tonight

Here comes Santa Claus, here comes Santa Claus right down Santa Claus Lane
He'll come around when chimes ring out, it's Christmas time again
Peace on earth will come to all, if we just follow the light
So let's give thanks to the Lord above 'cause Santa Claus comes tonight

Here comes Santa Claus, here comes Santa Claus right down Santa Claus Lane
He'll come around when chimes ring out, it's Christmas time again
Peace on earth will come to all, if we just follow the light
So let's give thanks to the Lord above 'cause Santa Claus comes tonight

Here comes Santa Claus, here comes Santa Claus right down Santa Claus Lane
Vixen and Blitzen and all his reindeer pullin' on the reins
Bells are ringin', children singin', all is merry and bright
So jump in bed, and cover your head, 'cause Santa Claus comes tonight

Peace on earth will come to all, if we just follow the light	
So let's give thanks to the Lord above 'cause Santa Claus comes tonight
So let's give thanks to the Lord above 'cause Santa Claus comes tonight
```



# Carol of the Bells (Shchedryk)


```
Hark how the bells, 
sweet silver bells, 
all seem to say, 
throw cares away
Christmas is here, 
bringing good cheer, 
to young and old, 
meek and the bold.

Ding dong ding dong 
that is their song 
with joyful ring 
all caroling.
One seems to hear 
words of good cheer 
from everywhere 
filling the air.

Oh how they pound, 
raising the sound, 
o'er hill and dale, 
telling their tale.

Gaily they ring 
while people sing 
songs of good cheer, 
Christmas is here.

Merry, Merry, Merry, Merry Christmas, 
Merry, Merry, Merry, Merry Christmas.

On on they send, 
on without end, 
their joyful tone 
to every home.
Ding dong ding... dong!

```
## Щедрик (Bountiful Night)

```
 (Ukrainian) 
Щедрик 

Щедрик, щедрик, щедрівочка,
Прилетіла ластівочка,
Стала собі щебетати,
Господаря викликати:
– Вийди, вийди, господарю,
Подивися на кошару,
Там овечки покотились,
А ягнички народились.
В тебе товар весь хороший,
Будеш мати мірку грошей.
Хоч не гроші, то полова,
В тебе жінка чорноброва.
Щедрик, щедрик, щедрівочка,
Прилетіла ластівочка.


```


## Chords
```
```


# It's the Most Wonderful Time of the Year

```
It's the most wonderful time of the year
With the kids jingle-belling
And everyone telling you
Be of good cheer
It's the most wonderful time of the year

[Verse]
It's the hap-happiest season of all
With those holiday greetings
And great happy meetings
When friends come to call
It's the hap-happiest season of all
There'll be parties for hosting
Marshmallows for roasting
And caroling out in the snow
There'll be scary ghost stories
And tales of the glories
Of Christmases long, long ago

[Chorus]
It's the most wonderful time of the year
There'll be much mistletoe-ing
And hearts will be glowing
When loved ones are near
It's the most wonderful time of the year
```


## Chords
```
```



# The Christmas Song (Merry Christmas to You) 

```
Chestnuts roasting on an open fire
Jack Frost nipping at your nose
Yuletide carols being sung by a choir
And folks dressed up like Eskimos
Everybody knows a turkey and some mistletoe
Can help to make the season bright
Tiny tots with their eyes all aglow
Will find it hard to sleep tonight

They know that Santa's on his way
He's loaded lots of toys and goodies on his sleigh
And every mother's child is gonna spy
To see if reindeer really know how to fly

And so I'm offering this simple phrase
To kids from one to ninety-two
Although it's been said many times, many ways
Merry Christmas to you

They know that Santa's on his way
With toys and goodies on his sleigh
And every mother's child is gonna spy
To see if reindeer really know how to fly

And so I'm offering this simple phrase
To kids from one to ninety-two
Although it's been said many times, many ways
Merry Christmas
Merry Christmas
Merry Christmas to you
```


## Chords
```
```


# Christmas Time

Bryan Adams

```
We waited all through the year
For the day to appear
When we could be together in harmony

You know the time will come
Peace on earth for everyone
And we can live forever in a world where we are free
Let it shine for you and me

There's something about Christmas time
Something about Christmas time
That makes you wish it was Christmas everyday

To see the joy in the children's eyes
The way that the old folks smile
Says that Christmas will never go away

We're all as one tonight
Makes no difference if you're black or white
'cause we can sing together in harmony

I know it's not too late
The world would be a better place
If we can keep the spirit more than one day in the year
Send a message loud and clear

  
Chorus:
It's the time of year when everyone's together
We'll celebrate here on Christmas day
When the ones you love are there
You can feel the magic in the air - you know it's everywhere
There's something about Christmas time
Something about Christmas time
That makes you wish it was Christmas every day

To see the joy in the children's eyes
The way that the old folks smile
Says that Christmas will never go away

```


## Chords
```
```


# Have Yourself A Merry Little Christmas

Sam Smith    
Songwriters: Hugh Martin / Ralph Blane

```
Have yourself a merry little Christmas
Let your heart be light
From now on your troubles will be out of sight

Have yourself a merry little Christmas
Make the Yuletide gay
From now on your troubles will be miles away

Here we are as in olden days
Happy golden days of yore
Faithful friends who are dear to us
Gather near to us once more

Through the years we all will be together
If the fates allow
Hang a shining star upon the highest place
So have yourself a merry little Christmas

Have yourself a merry little Christmas
So have yourself a merry little Christmas
```



## Chords
```
```




# It's Beginning to Look a Lot Like Christmas

Songwriter: Meredith Willson

```
It's beginning to look a lot like Christmas
Everywhere you go
Take a look at the five and ten, it's glistening once again
With candy canes and silver lanes that glow

It's beginning to look a lot like Christmas
Toys in every store
But the prettiest sight to see is the holly that will be
On your own front door

A pair of hop-a-long boots and a pistol that shoots
Is the wish of Barney and Ben
Dolls that'll talk and will go for a walk
Is the hope of Janice and Jen
And Mom and Dad can hardly wait for school to start again

It's beginning to look a lot like Christmas
Everywhere you go
There's a tree in the Grand Hotel, one in the park as well
It's the sturdy kind that doesn't mind the snow

It's beginning to look a lot like Christmas
Soon the bells will start
And the thing that will make 'em ring is the carol that you sing
Right within your heart

It's beginning to look a lot like Christmas
Toys in every store
But the prettiest sight to see is the holly that will be
On your own front door

Sure it's Christmas, once more
```

## Chords
```
```



# Le jour de l'An

```
- 1 -
 Préparons-nous, son père
 Pour fêter l' jour de l'An
 J'vais faire des bonnes tourtières
 Un bon ragoût d'l'ancien temps.

Refrain
 C'est dans l'temps du jour de l'An
 On s'donne la main, on s'embrasse
 C'est l'bon temps d'en profiter
 Ça arrive rien qu'une fois par année.

- 2 -
 Peinture ton "koteur"
 Va ferrer ta jument
 On ira voir ta soeur
 Dans l'fond du cinquième rang.

- 3 -
 Va t'acheter une perruque
 Fais-toi poser des dents
 C'est vrai t'as rien qu' moi à plaire 
 Mais tu s'rais plus ragoûtant.

- 4 -
 Ti-Blanc à ton oncle Nazaire
 Doit venir au jour de l'An
 Montres-y ton savoir-faire
 Comme tu dansais dans ton jeune temps.

- 5 -
 Tâche pas de perdre la tête
 Comme t'as fait il y a deux ans
 T'as commencé à voir clair
 Quand t'avais plus d'argent.

- 6 -
 Y'en a qui vont prendre un verre
 Y vont profiter de c'temps-là
 Aujourd'hui ça coûte si cher
 Y'a tant de monde qui travaille pas.

- 7 -
 Il y en a qui sentent la pipe
 Et d'autres qui sentent les oignons
 J'aime bien mieux vous l'dire tout-de-suite
 La plupart sentent la boisson.

Dernier refrain
 C'est dans l'temps du jour de l'An
 On s'donne la main, on s'embrasse
 C'est l'bon temps d'en profiter
 Ça dure rien qu'une fois par année.
```



## Chords
```
```
